apiVersion: v1
kind: Service
metadata:
  name: scaletestapp-service
  labels:
    app: scaletestapp
spec:
  type: NodePort  # NodePort для доступа через Minikube
  selector:
    app: scaletestapp
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http