apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletestapp
  template:
    metadata:
      labels:
        app: scaletestapp
    spec:
      containers:
      - name: scaletestapp
        image: polinux/stress  # Образ для генерации нагрузки на память
        command: ["sh", "-c"]
        args: 
        - |
          while true; do
            echo "Pod $(hostname) serving request"
            # Симуляция использования памяти
            if [ "$STRESS_MEMORY" = "true" ]; then
              stress --vm 1 --vm-bytes 25M --vm-hang 10 --timeout 30s
            fi
            sleep 5
          done
        resources:
          requests:
            memory: "20Mi"
            cpu: "50m"
          limits:
            memory: "30Mi"
            cpu: "100m"
        env:
        - name: STRESS_MEMORY
          value: "false"  # Будем включать через kubectl set env